defaults:
  - _self_
  - global_config

model_path: "./results/models/MIXLOSS_MSCLIP_SITS_ONLY/MSClipFacto-17-f1-0.43.ckpt" # Need to specify exact model path
config_name: "config_file.yaml"
mode: "image"
split: "test" # test
output_dir: "./results/models/MIXLOSS_MSCLIP_SITS_ONLY"
seed: 42
with_region: True
fwi_ths: [5, 10, 20, 30]
n_plots: 50
size_plots: 6
suffix: "one"

MODEL:
  architecture:  "MSClipFacto"
  model_name: Llama3-MS-CLIP-Base
  patch_size: 16
  pretrained: True
  ds_labels: True
  freeze_msclip: True
  input_img_res: 264
  img_res: 260
  train_max_seq_len: 5
  test_max_seq_len: 5
  val_max_seq_len: 5
  input_dim: 10
  num_classes: 2
  out_H: 26
  out_W: 26
  threshold: 0.5
  use_mixer: True
  use_doy: True
  use_cls_fusion: False
  upscale_factor: 1
  use_ln_norm_patch: False
  clearclip:
    enabled: False
    n_last: 1
    keep_ffn: False        # should be false for ClearCLIP
    keep_residual: False   # should be false for ClearCLIP
    attn_variant: "qq"
  vpt_config:
    enabled: False
    num_tokens: 20
    total_d_layer: 11

SOLVER:
  num_epochs: 20
  num_warmup_epochs: 2
  loss_function: combined_dice_ce

### Leveraging RAW *.npy files ###
DATASETS:
  kwargs:
    mean_file: "${paths.msclip_bands_mean}"
    std_file: "${paths.msclip_bands_std}"
    with_loc: False
    with_doy: True
    use_msclip_norm: True
    trans_type: "msclip"
    bands:
      - B2
      - B3
      - B4
      - B5
      - B6
      - B7
      - B8
      - B8A
      - B11
      - B12
  train:
    paths: "${paths.split_hard}"
    base_dir: ["${paths.pos_sits}", "${paths.neg_sits_hard}"]
    label_dir: "${paths.label}"
    batch_size: 24
    num_workers: 8

  eval:
    paths: "${paths.split_hard}"
    base_dir: ["${paths.pos_sits}", "${paths.neg_sits_hard}"]
    label_dir: "${paths.label}"
    batch_size: 24
    num_workers: 8
    hard: True

### Leveraging Hf parquet files ###
#DATASETS:
#  mode: "huggingface"
#  kwargs:
#    mean_file: "${paths.bands_mean}"
#    std_file: "${paths.bands_std}"
#    with_loc: False
#    with_doy: True
    # bands: possibility to specify the selected bands.
#  train:
#    data_dir: "${paths.hf_data}"
#    batch_size: 24
#    num_workers: 8
#
#  eval:
#    data_dir: "${paths.hf_data}"
#    batch_size: 24
#    num_workers: 8
#    hard: False